- frontend/src/api/calls/baseCalls.tsx
> fix infinite loop

- .github/workflows/java-test-coverage.yml
- backend/src/main/java/com/osoc6/OSOC6/database/models/Edition.java
- backend/src/main/java/com/osoc6/OSOC6/repository/EditionRepository.java
- backend/src/main/java/com/osoc6/OSOC6/repository/ProjectRepository.java
- backend/src/main/java/com/osoc6/OSOC6/repository/StudentRepository.java
- backend/src/main/java/com/osoc6/OSOC6/repository/UserRepository.java
- backend/src/main/java/com/osoc6/OSOC6/winterhold/MerlinSpELWizard.java
- backend/src/test/java/com/osoc6/OSOC6/adminTest/AdminUserEndpointTests.java
- backend/src/test/java/com/osoc6/OSOC6/coachTest/CoachUserEndpointTests.java
This issue implements the query by edition endpoint as asked in #295. https://github.com/SELab-2/OSOC-6/issues/295#issuecomment-1114600772
I ask reviewers to take special care looking at the tests.
> Add user query by edition endpoint

- backend/src/main/java/com/osoc6/OSOC6/database/models/Invitation.java
> change token from base64keygen to randomUUID

- backend/src/main/java/com/osoc6/OSOC6/database/models/UserEntity.java
- backend/src/main/java/com/osoc6/OSOC6/eventhandler/UserEntityEventHandler.java
- backend/src/main/java/com/osoc6/OSOC6/eventhandler/package-info.java
- backend/src/test/java/com/osoc6/OSOC6/adminTest/AdminUserEndpointTests.java
- backend/src/test/java/com/osoc6/OSOC6/coachTest/CoachUserEndpointTests.java
This pr closes #383. After this pr is merged, @ruvmello should be able to work on #310.
> Feature backend/383 encode pw user update

- frontend/locales/en/common.ts
- frontend/src/api/calls/baseCalls.tsx
- frontend/src/api/calls/communicationTemplateCalls.ts
- frontend/src/api/calls/editionCalls.ts
- frontend/src/handlers/createCommunicationTemplateSubmitHandler.ts
- frontend/src/pages/communicationTemplate/create.tsx
- frontend/src/properties/applicationPaths.ts
- frontend/test/createCommunicationTemplate.test.tsx
> CommunicationTemplate creation component

- frontend/src/components/profileOverview.tsx
- frontend/src/handlers/confirmResetHandler.ts
turns out it just works after kasper changed it. Just some other fix I noticed and did earlier on this branch is in here.
> Password Change

- frontend/locales/en/common.ts
- frontend/src/pages/_app.tsx
- frontend/src/pages/changeEmail.tsx
- frontend/src/pages/changePassword.tsx
- frontend/src/pages/home.tsx
- frontend/src/pages/index.tsx
- frontend/src/pages/login.tsx
- frontend/src/pages/loginError.tsx
- frontend/src/pages/profile.tsx
- frontend/src/pages/registration.tsx
- frontend/src/pages/users.tsx
- frontend/src/utility/stringUtil.ts
> Add favicon

- backend/src/main/java/com/osoc6/OSOC6/repository/StudentRepository.java
- backend/src/test/java/com/osoc6/OSOC6/adminTest/AdminStudentEndpointTests.java
This PR resolves https://github.com/SELab-2/OSOC-6/issues/295#issuecomment-1120403817.
> Add status filter

- frontend/locales/en/common.ts
- frontend/src/components/navBar.tsx
- frontend/src/components/optionsMenu.tsx
- frontend/src/components/profileOverview.tsx
- frontend/src/styles/optionsMenu.module.css
This is a option menu when you click the avatar icon. This PR has no tests as this is only visual change, the test coverage is the same because of this.
> Option Menu - Logout and Your profile

- backend/.gitignore
- backend/README.md
- backend/src/main/java/com/osoc6/OSOC6/configuration/WebConfiguration.java
- backend/src/main/java/com/osoc6/OSOC6/service/WebhookService.java
- backend/src/main/java/com/osoc6/OSOC6/webhook/FormField.java
- backend/src/main/java/com/osoc6/OSOC6/webhook/FormProcessor.java
- backend/src/main/java/com/osoc6/OSOC6/webhook/QuestionKey.java
- backend/src/main/resources/tally-ids.properties.example
- backend/src/test/java/com/osoc6/OSOC6/webhookTest/AddToStudentUnitTests.java
- backend/src/test/java/com/osoc6/OSOC6/webhookTest/FormFieldUnitTests.java
- backend/src/test/resources/tally-ids.properties
> Refactor webhook processing to use ids from properties file

- backend/src/main/java/com/osoc6/OSOC6/repository/SkillTypeRepository.java
- backend/src/test/java/com/osoc6/OSOC6/coachTest/CoachSkillTypeEndpointTests.java
This issue solves https://github.com/SELab-2/OSOC-6/issues/295#issuecomment-1126691379
> coach enable all skillTypes

- frontend/src/api/calls/userCalls.ts
- frontend/src/components/util/navBar.tsx
- frontend/src/components/util/optionsMenu.tsx
- frontend/src/handlers/loginSubmitHandler.tsx
- frontend/src/pages/assignStudents.tsx
- frontend/src/pages/index.tsx
- frontend/test/integration/login.test.tsx
This PR introduces some utility improvements so users don't get lost in the application.
> Usability impovements

- frontend/src/components/student/studentFilterComponent.tsx
- frontend/test/integration/student/studentFilter.test.tsx
- frontend/test/integration/studentList.test.tsx
This PR aims to implement the studentFilterComponent tests of #360.
> Student filter component tests

- frontend/src/api/calls/editionCalls.ts
- frontend/src/components/project/createProjectForm.tsx
- frontend/src/components/projectAssignment/assignmentStudentRow.tsx
- frontend/src/components/util/routeInjector.tsx
- frontend/src/context/globalContext.tsx
- frontend/src/handlers/createProjectSubmitHandler.tsx
- frontend/src/hooks/useGlobalEdition.ts
- frontend/src/hooks/utilHooks.ts
- frontend/test/integration/Provide.tsx
- frontend/test/integration/createProjectForm.test.tsx
- frontend/test/integration/routeInjector.test.tsx
This issue partly fixed #452 but not completely. A complete fix seems impossible (https://github.com/SELab-2/OSOC-6/issues/452#issuecomment-1128963467).
> Fix useEdition

- frontend/src/components/util/routeInjector.tsx
- frontend/src/context/globalContext.tsx
> Broken edition when no edition exists on url

- frontend/locales/en/common.ts
- frontend/src/components/student/studentInfo.tsx
> Add missing translations

- backend/src/main/java/com/osoc6/OSOC6/entities/Assignment.java
- backend/src/main/java/com/osoc6/OSOC6/repository/AssignmentRepository.java
- backend/src/main/java/com/osoc6/OSOC6/winterhold/DumbledorePathWizard.java
- backend/src/test/java/com/osoc6/OSOC6/TestEntityProvider.java
- backend/src/test/java/com/osoc6/OSOC6/adminTest/AdminAssignmentEndpointTests.java
- backend/src/test/java/com/osoc6/OSOC6/adminTest/AdminCommunicationEndpointTests.java
- backend/src/test/java/com/osoc6/OSOC6/adminTest/AdminStudentEndpointTests.java
- backend/src/test/java/com/osoc6/OSOC6/adminTest/AdminSuggestionEndpointTests.java
- backend/src/test/java/com/osoc6/OSOC6/coachTest/CoachAssignmentEndpointTests.java
- backend/src/test/java/com/osoc6/OSOC6/coachTest/CoachCommunicationEndpointTests.java
- backend/src/test/java/com/osoc6/OSOC6/coachTest/CoachStudentEndpointTests.java
- backend/src/test/java/com/osoc6/OSOC6/coachTest/CoachSuggestionEndpointTests.java
This PR resolves https://github.com/SELab-2/OSOC-6/issues/295#issuecomment-1129734948. This way we can query only the valid assignments of a student.
> Valid assignments endpoint

- backend/src/main/java/com/osoc6/OSOC6/entities/Assignment.java
- backend/src/main/java/com/osoc6/OSOC6/entities/Communication.java
- backend/src/main/java/com/osoc6/OSOC6/entities/CommunicationTemplate.java
- backend/src/main/java/com/osoc6/OSOC6/entities/Edition.java
- backend/src/main/java/com/osoc6/OSOC6/entities/Invitation.java
- backend/src/main/java/com/osoc6/OSOC6/entities/Project.java
- backend/src/main/java/com/osoc6/OSOC6/entities/ProjectSkill.java
- backend/src/main/java/com/osoc6/OSOC6/entities/ResetPasswordToken.java
- backend/src/main/java/com/osoc6/OSOC6/entities/SkillType.java
- backend/src/main/java/com/osoc6/OSOC6/entities/Suggestion.java
- backend/src/main/java/com/osoc6/OSOC6/entities/UserEntity.java
- backend/src/main/java/com/osoc6/OSOC6/entities/UserSkill.java
- backend/src/main/java/com/osoc6/OSOC6/entities/student/Student.java
- backend/src/main/resources/application.properties.example
- backend/src/main/resources/data.sql
> Feature backend/453 load base data

- frontend/src/components/student/studentInfo.tsx
- frontend/src/pages/students/[id].tsx
- frontend/src/pages/students/index.tsx
- frontend/src/styles/pageGrids.module.css
Fixes some mistakes in the styling due to early merge. Builds upon #457
> Quick fixes to layout

- frontend/public/resources/link.svg
- frontend/src/components/user/loginForm.tsx
- frontend/src/components/util/background.tsx
- frontend/src/pages/login.tsx
- frontend/src/styles/background.module.css
- frontend/src/styles/loginForm.module.css
This PR contains the restyling of the login page.
This includes but is not limited to:
- centering everything dynamically
- adding icons (forgot password)
- changing colors
Linked to issue #457
> Feature frontend/457 styling login

- frontend/locales/en/common.ts
- frontend/src/components/conflictResolution/conflictResolutionItem.tsx
- frontend/src/components/conflictResolution/conflictResolutionList.tsx
- frontend/src/components/conflictResolution/conflictResolutionRadioButton.tsx
- frontend/src/styles/conflicts.module.css
Styling for the conflict component
> Styling conflicts

- frontend/src/components/communication/communicationList.tsx
- frontend/src/components/communication/communicationListItem.tsx
- frontend/src/components/communication/communicationTemplateList.tsx
- frontend/src/components/communication/createCommunicationForm.tsx
- frontend/src/components/communication/createCommunicationTemplateForm.tsx
- frontend/src/pages/communicationTemplates/[id].tsx
- frontend/src/pages/communicationTemplates/[id]/edit.tsx
- frontend/src/pages/communicationTemplates/create.tsx
- frontend/src/pages/communicationTemplates/index.tsx
- frontend/src/pages/communications/[id].tsx
- frontend/src/pages/students/[id]/communications.tsx
- frontend/src/pages/students/[id]/register-communication.tsx
> Document communication

- frontend/src/components/user/registrationForm.tsx
- frontend/src/components/util/forgotComponent.tsx
- frontend/src/components/util/resetComponent.tsx
- frontend/src/pages/changeEmail.tsx
- frontend/src/pages/changePassword.tsx
- frontend/src/pages/forgotPassword.tsx
- frontend/src/pages/registration.tsx
- frontend/src/pages/resetPassword.tsx
- frontend/src/styles/pageGrids.module.css
- frontend/src/styles/resetComponent.module.css
Change layout of:
changeEmail, changePassword, forgotPassword, registration, resetPassword
> Add layout to all change... pages

- frontend/src/components/projectAssignment/assignmentStudentRow.tsx
- frontend/src/components/projectAssignment/projectAssignmentList.tsx
- frontend/src/styles/assignments.module.css
- frontend/src/styles/globals.css
Current styling:
(Assign students only)
> Feature frontend/457 styling assign students

- frontend/src/components/edition/editionOverview.tsx
- frontend/src/components/edition/editionRowComponent.tsx
- frontend/src/components/user/manageUserComponent.tsx
- frontend/src/pages/editions/[id].tsx
- frontend/src/pages/profile.tsx
- frontend/src/styles/editionList.module.css
- frontend/src/styles/profileOverview.module.css
Styling + view from overview (the eye) + some minor things
> Edition overview

- frontend/locales/en/common.ts
- frontend/src/components/edition/editionRowComponent.tsx
A toast is now shown when an attempt to delete a not empty edition is made.
> Delete not empty edition

- backend/src/main/java/com/osoc6/OSOC6/repository/StudentRepository.java
- backend/src/test/java/com/osoc6/OSOC6/adminTest/AdminAssignmentEndpointTests.java
> ignore invalid

- frontend/src/api/calls/studentCalls.ts
- frontend/src/components/student/studentFilterComponent.tsx
- frontend/src/components/student/studentList.tsx
- frontend/test/integration/student/studentList.test.tsx
> Student filter other skilltype

- frontend/locales/en/common.ts
- frontend/src/components/student/createStudentForm.tsx
- frontend/src/styles/students/studentCreate.module.css
- frontend/src/utility/stringUtil.ts
> Add more input validation for email and URI's in the student creation form

- frontend/src/components/skillType/skillTypeForm.tsx
- frontend/src/components/skillType/skillTypeListItem.tsx
- frontend/src/pages/skillTypes/create.tsx
- frontend/src/pages/skillTypes/index.tsx
- frontend/src/styles/skillTypes.module.css
- frontend/test/integration/student/editStudent.test.tsx
Skilltype page styling (components were already styled)
> Skilltype page styling

- backend/README.md
> add docs about data.sql

- frontend/locales/en/common.ts
- frontend/src/pages/forgotPassword.tsx
- frontend/src/pages/login.tsx
> add link back to login

- frontend/src/components/projectAssignment/assignmentReasonListItem.tsx
- frontend/src/components/util/routeInjector.tsx
- frontend/test/integration/assignments/assignmentItem.test.tsx
A coach saw some stuff it should not
> Coach view

- backend/src/main/java/com/osoc6/OSOC6/repository/UserRepository.java
- backend/src/test/java/com/osoc6/OSOC6/adminTest/AdminUserEndpointTests.java
- backend/src/test/java/com/osoc6/OSOC6/coachTest/CoachUserEndpointTests.java
This is part of #510. Admins and coaches can delete themselves now (admin only if they are not the last remaining admin). Admins can also delete anyone.
> user can delete themselves, admin can delete anyone

- frontend/src/components/conflictResolution/conflictResolutionItem.tsx
Removes resolve button for coaches
> Coach resolve button gone

- frontend/src/components/project/projectForm/projectForm.tsx
- frontend/src/styles/projects/createProject.module.css
- frontend/src/utility/stringUtil.ts
- frontend/test/integration/TestEntityProvider.ts
> Add URI validation to project creation form
